### PR TITLE
Update resume.template to Use {{resume.basics.picture}} and {{resume.basics.name}} in place of hardcoded image.

### PR DESCRIPTION
**Pull request by mcarbonneaux**
Use {{resume.basics.picture}} and {{resume.basics.name}} in place of hardcoded image.

### CODE REVIEW

**Comment by nabilbendafi** [comment]
Thanks for you interest.

**Comment by mcarbonneaux** [comment]
when this update while be used by https://registry.jsonresume.org ?

because when use for my jsonresume:
https://registry.jsonresume.org/mcarbonneaux?theme=onepageresume

they continue to use chtulu !

they dont need update npm registry ? https://www.npmjs.com/package/jsonresume-theme-onepage

**Comment by nabilbendafi** [comment]
> In short, if you want to add a theme to the official list, you need to publish an npm module named `jsonresume-theme-{name}`. That module needs to export a function called `render` that takes a `resume.json` and returns a plain html string.

You are using the `onepageresume` theme, so npm package is https://www.npmjs.com/package/jsonresume-theme-onepageresume (which is available in https://registry.jsonresume.org/themes and it works, because you can see the _Cthulu_) and not https://www.npmjs.com/package/jsonresume-theme-onepage (ie `onepage`).

I've published new version of `onepageresume` on NPM. So now, why this new version is not taken into account is out of my hands. I'm not delivering `Jsonresume` online hosting.

Please eventually open PR on https://github.com/jsonresume/registry-functions (hint: https://github.com/jsonresume/registry-functions/blob/98fa2b58dca2b48ef2ac207262333b53ee8b5aef/functions/package.json#L51).

**Comment by mcarbonneaux** [comment]
sorry i've not sended the good npm url ! 
ok we need update of the version in https://github.com/jsonresume/registry-functions/blob/master/functions/package.json !
`"jsonresume-theme-onepageresume": "0.0.2",` to `"jsonresume-theme-onepageresume": "0.0.3",`

**Comment by mcarbonneaux** [comment]
i've made PR to that : https://github.com/jsonresume/registry-functions/pull/47 
i've used `^` to make possible to update the minor version without need of new pull request.

**Pull request merged**
